CREATE TABLE IF NOT EXISTS BUG (
    COUNTER_ID INTEGER AUTO_INCREMENT, 
    BUG_ID INTEGER, 
    TITLE VARCHAR,
    STATUS VARCHAR,
    OWNER VARCHAR,
    TYPE_PRIORITY VARCHAR,
    PRIORITY VARCHAR,
    COMPONENT VARCHAR,
    CLOSED_DATE DATETIME NULL,
    STARS INTEGER CHECK(STARS >=0),
    REPORTED_BY VARCHAR,
    OPENED_DATE DATETIME,		
    DESCRIPTION VARCHAR, 

    PRIMARY KEY (COUNTER_ID)
);


CREATE TABLE IF NOT EXISTS COMMENT (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    BUG_ID INTEGER,
    AUTHOR VARCHAR,
    WHEN DATETIME,
    WHAT VARCHAR,

    PRIMARY KEY(COUNTER_ID),
    FOREIGN KEY(BUG_ID) REFERENCES BUG(COUNTER_ID) ON DELETE CASCADE	
);


CREATE TABLE IF NOT EXISTS DOCUMENT (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    DOC_DATE DATETIME,
    DOC_TEXT VARCHAR,

    PRIMARY KEY(COUNTER_ID)
);


CREATE TABLE IF NOT EXISTS TERM (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    WORD VARCHAR,       

    PRIMARY KEY(WORD)        
);


CREATE TABLE IF NOT EXISTS VERSION (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    STEP_TYPE VARCHAR,
    STEP INTEGER,
    DATE_FROM DATETIME,
    DATE_TO DATETIME,
    
    PRIMARY KEY(COUNTER_ID)    
);


CREATE TABLE IF NOT EXISTS VERSION_DOC (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    VERSION_ID INTEGER,
    DOC_ID INTEGER,

    PRIMARY KEY(COUNTER_ID),
    FOREIGN KEY(VERSION_ID) REFERENCES VERSION(COUNTER_ID) ON DELETE CASCADE,
    FOREIGN KEY(DOC_ID) REFERENCES DOCUMENT(COUNTER_ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS TOPIC (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    #VERSION_ID INTEGER,	

    PRIMARY KEY(COUNTER_ID)
    #FOREIGN KEY(VERSION_ID) REFERENCES VERSION(COUNTER_ID)	
);


CREATE TABLE IF NOT EXISTS TOPIC_TERM (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    TOPIC_ID INTEGER,
    TERM_ID VARCHAR,
    #VERSION_ID INTEGER,		
    PROBABILITY DECIMAL(18, 9),

    PRIMARY KEY(TOPIC_ID, TERM_ID),
    FOREIGN KEY(TERM_ID) REFERENCES TERM(WORD) ON DELETE CASCADE,
    FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC(COUNTER_ID) ON DELETE CASCADE
    #FOREIGN KEY(VERSION_ID) REFERENCES VERSION(COUNTER_ID)
);


CREATE TABLE IF NOT EXISTS TOPIC_DOCUMENT (
    COUNTER_ID INTEGER AUTO_INCREMENT,
    DOC_ID INTEGER,
    TOPIC_ID INTEGER,
    #VERSION_ID INTEGER,	
    PROBABILITY DECIMAL(18, 9),

    PRIMARY KEY(TOPIC_ID, DOC_ID),
    FOREIGN KEY(DOC_ID) REFERENCES DOCUMENT(COUNTER_ID) ON DELETE CASCADE,
    FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC(COUNTER_ID) ON DELETE CASCADE
    #FOREIGN KEY(VERSION_ID) REFERENCES VERSION(COUNTER_ID)
);

#CREATE TABLE IF NOT EXISTS TOPIC_FINAL (
    #COUNTER_ID ,
    #VERSION_ID INTEGER,	

    #PRIMARY KEY(COUNTER_ID),
    #FOREIGN KEY(VERSION_ID) REFERENCES TOPIC(COUNTER_ID)
    #FOREIGN KEY(VERSION_ID) REFERENCES VERSION(COUNTER_ID)	
#);

